title: My Portfolio
logo: /posts/images/logo.png
description: "A personal portfolio showcasing my skills in data analysis and natural language processing. See my latest projects and professional journey."

 
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

